slogan: â€œæ›©å–†å¤šé—å°˜ï¼Œæ¸…é£æ¥å››éš…â€
email: zwz0123460218@icloud.com
logo: "/images/logo.svg"

mathjax: false # åŠ è½½ LateX æ•°å­¦å…¬å¼åº“

favicon: # é…ç½®ç½‘é¡µå›¾æ ‡
  small: /images/favicon-16x16.png
  medium: /images/favicon-32x32.png
  apple_touch_icon: /images/apple-touch-icon.png
  safari_pinned_tab: /images/logo.svg

subpage: # å¼€å¯â€œå­é¡µâ€åŠŸèƒ½ï¼Œè¯¦è§ README
  enable: true
  pages:
    - name: traveling
      path: https://www.travellings.cn/go.html 
      title: ğŸš‡ 
    - name: article 
      title: æ–‡ç«  
      icon: /images/icon/icon-article.svg 
      description: 'åšä¸»æ˜¯åšåç«¯å¼€å‘çš„ï¼Œä¸»è¦æ˜¯å¤§å‹åˆ†å¸ƒå¼é¡¹ç›®å’Œæ•°æ®å¤„ç†ç›¸å…³ç»éªŒã€‚åœ¨è¿™é‡Œä¼šè®°å½•ä¸€äº›è‡ªå·±çš„è¸©å‘ç»å†ï¼Œåˆ†äº«ä¸€äº›ä¼˜è´¨çš„é¡¹ç›®è®¾è®¡æ–¹æ¡ˆã€‚'
    - name:  event
      title: æ—¥è®°
      icon: /images/icon/icon-event.svg
      description: 'æˆ‘æ˜¯ä¸ªå¾ˆæ€€æ—§çš„äººï¼Œåœ¨è¿™é‡Œå†™ä¸‹æ¯ä¸ªé˜¶æ®µçš„æ„Ÿæ‚Ÿã€‚å¸Œæœ›ä»¥åå›é¦–çš„æ—¶å€™ï¼Œéƒ½è¿˜æ˜¯ä»å‰é‚£ä¸ªå°‘å¹´ã€‚'
    - name:  comment
      title: ç•™è¨€æ¿
      path: /page/comment
index: # é…ç½®é¦–é¡µä¸ªæ€§åŒ–å†…å®¹
  motto: "ä¸­äºŒç—…ä¹Ÿè¦å¤ªæ‹çˆ±ï¼"
  poem:
    - å´©è£‚å§ç²¾ç¥
    - å´©è£‚å§ç²¾ç¥
  photo: /images/about.jpg
  about:
    title: å…³äºæˆ‘
    text:
      - INFJ | çŒ«å¥´ | ç å†œ | äºŒæ¬¡å…ƒ
      - å¹³æ—¶å®…å®¶é‡Œæ‰“ç‹è€…ã€kæ­Œ
      - æ¢¦æƒ³æ˜¯æ‰“å¡ä¸–ç•Œå„åœ°ï½

foot:
  title:
    - "æ›©å–†å¤šé—å°˜"
    - "æ¸…é£æ¥å››éš…"
  linksRows: 4

links: # æœ‹å‹
  - name: "äº‘æ¸¸å›"
    url: https://www.yunyoujun.cn/
  - name: "bootun"
    url: https://github.com/bootun/
  - name: "NingBo Wang"
    url: https://github.com/hqwangningbo

social:
  - name: "Vingur Zhou"
    icon: "/images/logo-github.svg"
    url: https://github.com/Vingurzhou

contacts:
  - name: "zwz0123460218@icloud.com"
    icon: "/images/icon/icon-email.svg"
    url: "mailto:zwz0123460218@icloud.com"

reward: # èµèµ
  enable: false
  face: /assets/author-face.jpg # å¤´åƒå›¾ç‰‡
  paycode: /assets/pay-code.jpg # æ”¯ä»˜ç å›¾ç‰‡
  text: â€œç»™ä½œè€…å€’æ¯å¡å¸ƒå¥‡è¯ºâ€
  btnText: å–œæ¬¢ä½œè€…

# see https://github.com/gitalk/gitalk
gitalk: # gitalk è¯„è®º
  enable: true
  owner: Vingurzhou
  admin: Vingurzhou
  repo: vingurzhou.github.io
  clientID: Ov23liNUccG2yvllnzXb
  clientSecret: eb0dcf185b111188127a7c856c001c376416eba0

  distractionFreeMode: false # Facebook-like distraction free mode
  # When the official proxy is not available, you can change it to your own proxy address
  proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token # This is official proxy address
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en | es-ES | fr | ru | zh-CN | zh-TW
  language: zh-CN

# see https://github.com/tea3/hexo-related-popular-posts
related_post:
  enable: false
  config:
    maxCount: 5 # Maximum count of a list. default 5
    ulClass: # Class name of element. default 'popular-posts'
    PPMixingRate: 0.4 # Mixing ratio of popular posts and related posts. default 0.0(=Related posts only)
    isDate: # visible the date. false
    isImage: # visible the image. false
    isExcerpt: # visible the excerpt. false
    PPCategoryFilter: # Option to fix category on Popular Posts. undefined
    PPTagFilter: # Option to fix tag on Popular Posts. undefined

# Baidu Webmaster tools verification.
# See: https://ziyuan.baidu.com/site
baidu_site_verification:

# Baidu Analytics
# See: https://tongji.baidu.com
baidu_analytics: # <app_id>

# è‡ªå®šä¹‰å­—ä½“ï¼Œç”¨äºç¾åŒ–éƒ¨åˆ†æ±‰å­—çš„æ˜¾ç¤ºæ•ˆæœ.
# å¯ä»¥é€šè¿‡æ›¿æ¢ _font/ ç›®å½•ä¸‹çš„å­—ä½“æ–‡ä»¶æ›¿æ¢è‡ªå·±å–œæ¬¢çš„å­—ä½“
zh_font:
  enable: true
  fontName: sourceHanSerif
  type: ttf
  style:
    - normal
    - bold

# é…ç½®æ—¶é—´çº¿ å‚è€ƒ README.md
timeline:
  enable: true
  order: false # æ˜¯å¦æŒ‰æ—¶é—´æ­£åºå±•ç¤ºï¼Œfalse ä¸ºå€’åº
  items:
    - name: article
      color: "#ee936c"
      icon: /images/icon/icon-article.svg
      checked: true
    - name: app
      color: "#60a465"
      icon: /images/icon/icon-app.svg
      checked: true
    - name: event
      color: "#568dc4"
      icon: /images/icon/icon-event.svg
      checked: true

# æ ‡ç­¾äº‘
tagcloud:
  fancy: false
  min_font: 14
  max_font: 30

mermaid:
  enable: true # å¯ç”¨ Mermaid å¢å¼º
  version: latest
  options:
    startOnload: true

search:
  path: search.json
  enable: true
  field: post
  content: true

nav:
  sticky: false
